
import React, { useEffect, useState } from 'react';
import { ArrowLeft, BookOpen, Loader2, Share2, Printer } from 'lucide-react';
import { Button } from './Button';
import { ResourceItem, Language } from '../types';
import { generateLessonContent } from '../services/geminiService';

interface LearningPageProps {
  resource: ResourceItem | { title: string; description?: string };
  language: Language;
  onBack: () => void;
}

export const LearningPage: React.FC<LearningPageProps> = ({ resource, language, onBack }) => {
  const [content, setContent] = useState<string>('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchContent = async () => {
      setLoading(true);
      // Simulate loading slightly for UX if it's too fast
      const [generatedText] = await Promise.all([
        generateLessonContent(resource.title, language),
        new Promise(resolve => setTimeout(resolve, 600))
      ]);
      setContent(generatedText);
      setLoading(false);
    };

    fetchContent();
  }, [resource, language]);

  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <Button variant="ghost" onClick={onBack} className="mb-6 pl-0 hover:bg-transparent hover:text-emerald-700">
        <ArrowLeft className="mr-2" size={20} />
        Back to Portal
      </Button>

      <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden min-h-[60vh]">
        {/* Header */}
        <div className="bg-emerald-600 p-8 text-white">
          <div className="flex items-start justify-between">
            <div>
               <div className="flex items-center gap-2 mb-3 opacity-90">
                <BookOpen size={20} />
                <span className="text-sm font-medium uppercase tracking-wider">Learning Module</span>
              </div>
              <h1 className="text-3xl md:text-4xl font-bold mb-4">{resource.title}</h1>
              {/* @ts-ignore */}
              {resource.description && <p className="text-emerald-100 text-lg max-w-2xl">{resource.description}</p>}
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="p-8 md:p-12">
          {loading ? (
            <div className="flex flex-col items-center justify-center py-20 space-y-4">
              <Loader2 className="animate-spin text-emerald-600" size={48} />
              <p className="text-slate-500 animate-pulse">Preparing your lesson...</p>
            </div>
          ) : (
            <article className="prose prose-slate prose-lg max-w-none">
              {/* Simple parser for bolding and newlines since we aren't using a markdown library */}
              {content.split('\n').map((line, i) => {
                if (line.startsWith('## ') || line.startsWith('### ')) {
                  return <h3 key={i} className="text-xl font-bold text-slate-800 mt-6 mb-3">{line.replace(/#+ /, '')}</h3>;
                }
                if (line.match(/^\d\./)) {
                   return <div key={i} className="flex gap-2 mb-2"><span className="font-bold text-emerald-700 min-w-[20px]">{line.split('.')[0]}.</span><span>{line.substring(line.indexOf('.') + 1)}</span></div>
                }
                if (line.startsWith('- ')) {
                    return <li key={i} className="ml-4 mb-1 list-disc text-slate-700">{line.substring(2)}</li>
                }
                if (line.trim() === '') {
                    return <br key={i} />
                }
                // Check for **bold** text
                const parts = line.split('**');
                return (
                  <p key={i} className="mb-4 text-slate-700 leading-relaxed">
                    {parts.map((part, index) => 
                      index % 2 === 1 ? <strong key={index} className="text-slate-900">{part}</strong> : part
                    )}
                  </p>
                );
              })}
            </article>
          )}
        </div>

        {/* Footer Actions */}
        {!loading && (
          <div className="bg-slate-50 border-t border-slate-100 p-6 flex justify-between items-center">
            <p className="text-sm text-slate-500">Content generated by AI Assistant</p>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={() => window.print()}>
                <Printer size={16} className="mr-2" />
                Print
              </Button>
              <Button variant="secondary" size="sm">
                <Share2 size={16} className="mr-2" />
                Share
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
